# Generated by Django 5.2.3 on 2025-06-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_download_notice_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
