# Generated by Django 5.2.3 on 2025-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organizationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetail',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
