# Generated by Django 5.2.3 on 2025-07-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organizationdetail_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
